const fullBeerGuidelines = [
    {
        name: "1A. American Light Lager",
        stats: "OG: 1.028–1.040 | FG: 0.998–1.008 | IBU: 8–12 | SRM: 2–3 | ABV: 2.8–4.2%",
        impression: "Highly carbonated, very light-bodied, highly refreshing lager engineered to have virtually no flavor or aroma profile.",
        aroma: "Low to no malt; faint corn or DMS notes optional. Hop aroma absent.",
        appearance: "Very pale straw to pale yellow color. White, fleeting head.",
        flavor: "Relatively neutral palate with crisp, dry finish and very low bitterness.",
        mouthfeel: "Very light body. High carbonation with slight carbonic bite.",
        comments: "Designed for mass appeal and maximum thirst-quenching refreshment.",
        history: "Evolution of American standard lagers influenced by industrial brewing.",
        ingredients: "Two-row or six-row barley, up to 40% corn or rice adjuncts.",
        comparison: "Lighter in body, alcohol, and flavor than standard American Lager."
    },
    {
        name: "3B. Czech Premium Pale Lager",
        stats: "OG: 1.044–1.060 | FG: 1.013–1.017 | IBU: 30–45 | SRM: 3.5–6 | ABV: 4.2–5.8%",
        impression: "Rich, complex, bready pale lager with high drinkability and smooth Saaz hop balance.",
        aroma: "Rich bready malt combined with spicy, floral Saaz hops. Trace diacetyl acceptable.",
        appearance: "Deep gold to pale amber, dense creamy head.",
        flavor: "Complex malt profile with bready sweetness transitioning to smooth herbal bitterness.",
        mouthfeel: "Medium to medium-full body, smooth rounded carbonation.",
        comments: "Known locally as Svetly Lezak (Plzner type).",
        history: "Pioneered in 1842 in Pilsen by Josef Groll.",
        ingredients: "Moravian malt, Saaz hops, soft Pilsen water, Czech lager yeast.",
        comparison: "Bigger, richer, and less crisp/dry than a German Pils."
    },
    {
        name: "5D. German Pils",
        stats: "OG: 1.044–1.050 | FG: 1.008–1.013 | IBU: 22–40 | SRM: 2–5 | ABV: 4.4–5.2%",
        impression: "Crisp, clean, bright golden lager with prominent noble hop bitterness and aroma.",
        aroma: "Medium-low noble hop aroma (floral/spicy). Clean grainy malt base.",
        appearance: "Straw to deep gold, brilliant clarity, creamy head.",
        flavor: "Medium to high hop bitterness with crisp, dry, clean finish.",
        mouthfeel: "Medium-light body, high carbonation, crisp.",
        comments: "The premier German hopped lager style.",
        history: "Adapted from Czech Pilsner to suit German palate and sulfate water.",
        ingredients: "Pilsner malt, German noble hops, clean lager yeast.",
        comparison: "Drier, crisper, and more bitter than Czech Pale Lager."
    },
    {
        name: "6A. Märzen",
        stats: "OG: 1.054–1.060 | FG: 1.010–1.014 | IBU: 18–24 | SRM: 8–17 | ABV: 5.6–6.0%",
        impression: "Rich, toasted German amber lager with clean malt complexity and smooth finish.",
        aroma: "Rich German malt aroma (toasty, bready, slightly sweet). No roast or caramel.",
        appearance: "Deep amber to copper, brilliant clarity, persistent off-white head.",
        flavor: "Soft, elegant malt complexity with medium-dry finish and low bitterness.",
        mouthfeel: "Medium body, smooth creamy texture.",
        comments: "Traditionally brewed in March and lagered for Oktoberfest.",
        history: "Originated in Bavaria as a strong storage beer.",
        ingredients: "Munich and Vienna malts, German noble hops, lager yeast.",
        comparison: "Richer and darker than Festbier or Helles."
    },
    {
        name: "9A. Doppelbock",
        stats: "OG: 1.072–1.112 | FG: 1.016–1.024 | IBU: 16–26 | SRM: 6–25 | ABV: 7.0–10.0%",
        impression: "Very strong, rich, malty German lager with deep melanoidins and warming alcohol.",
        aroma: "Intense Munich malt aroma (toasty, dark fruit, bread crust). No roast.",
        appearance: "Deep copper to dark brown, thick creamy head.",
        flavor: "Rich, complex malt dominance with dark fruit flavors (raisin, plum).",
        mouthfeel: "Full body, smooth warming alcohol finish without harshness.",
        comments: "Names often end in '-ator'.",
        history: "Invented by Paulaner monks in Munich as liquid bread for fasting.",
        ingredients: "Heavy Munich and Vienna base malts, German hops.",
        comparison: "Stronger, darker, and richer than Bock or Helles Bock."
    },
    {
        name: "10A. Weissbier",
        stats: "OG: 1.044–1.052 | FG: 1.010–1.014 | IBU: 8–15 | SRM: 2–6 | ABV: 4.3–5.6%",
        impression: "Bavarian wheat ale with prominent banana and clove yeast character, highly carbonated.",
        aroma: "Moderate to strong banana ester and spicy clove phenol.",
        appearance: "Pale straw to amber, very cloudy with yeast, massive rocky white head.",
        flavor: "Banana and clove prominent, balanced by soft wheat sweetness.",
        mouthfeel: "Medium-light to medium body, creamy effervescent mouthfeel.",
        comments: "Must contain at least 50% malted wheat.",
        history: "Bavarian wheat beer tradition protected by historical brewing laws.",
        ingredients: "Malted wheat (50%+), pilsner malt, German wheat beer yeast.",
        comparison: "Distinctly more phenolic and ester-driven than American Wheat."
    },
    {
        name: "11B. Best Bitter",
        stats: "OG: 1.040–1.048 | FG: 1.004–1.012 | IBU: 25–40 | SRM: 8–16 | ABV: 3.8–4.6%",
        impression: "Flavorful, sessionable British ale with balanced malt depth and moderate hop bitterness.",
        aroma: "Low to moderate fruity esters (plum, berry), earthy/floral hops, light biscuit malt.",
        appearance: "Medium amber to copper, low carbonation, off-white head.",
        flavor: "Medium bready/caramel malt balanced with earthy hop bitterness and dry finish.",
        mouthfeel: "Medium-light body, low carbonation traditional cask feel.",
        comments: "The benchmark British pub session ale.",
        history: "Grew out of pale ale taxes and duty structures in the UK.",
        ingredients: "British pale ale malt, crystal malts, English ale yeast, UK hops.",
        comparison: "Stronger than Ordinary Bitter; lower gravity than Strong Bitter."
    },
    {
        name: "11C. Strong Bitter",
        stats: "OG: 1.048–1.060 | FG: 1.008–1.012 | IBU: 30–50 | SRM: 8–18 | ABV: 4.6–6.2%",
        impression: "Assertive British pale ale with substantial malt backing and prominent English hops.",
        aroma: "Moderate fruitiness, pronounced earthy/floral British hop aroma, biscuity malt.",
        appearance: "Deep amber to light copper, clear, moderate head.",
        flavor: "Rich malt profile (caramel, bread, nuts) balanced by firm hop bitterness.",
        mouthfeel: "Medium body, smooth texture.",
        comments: "Also known as Extra Special Bitter (ESB) in commercial context.",
        history: "Scaled-up bitter version for winter or export strength.",
        ingredients: "British pale malts, crystal/amber malts, Fuggles/Goldings hops.",
        comparison: "Richer, stronger, and more assertive than Best Bitter."
    },
    {
        name: "15B. Irish Stout",
        stats: "OG: 1.036–1.044 | FG: 1.007–1.011 | IBU: 25–45 | SRM: 25–40 | ABV: 4.0–4.5%",
        impression: "Black, roasty, dry ale with creamy head and sharp coffee-like roasted barley bitterness.",
        aroma: "Coffee-like roasted barley aroma, low dark chocolate notes.",
        appearance: "Jet black with ruby highlights, creamy persistent white/tan head.",
        flavor: "Moderate to high roasted barley astringency and bitterness, dry coffee-like finish.",
        mouthfeel: "Medium-light to medium body, smooth creamy mouthfeel.",
        comments: "Guinness is the classic commercial exemplar.",
        history: "Irish adaptation of London porter styles utilizing roasted unmalted barley.",
        ingredients: "Pale ale malt, flaked barley, roasted barley, Irish ale yeast.",
        comparison: "Drier and sharper roast bite than English Porter or Sweet Stout."
    },
    {
        name: "20A. American Porter",
        stats: "OG: 1.050–1.070 | FG: 1.012–1.018 | IBU: 25–50 | SRM: 22–40 | ABV: 4.8–6.5%",
        impression: "Substantially roasty dark ale with chocolate/caramel notes and clean American profile.",
        aroma: "Medium-low chocolate and caramel malt notes, light American hop aroma optional.",
        appearance: "Dark brown to black, clear, tan head.",
        flavor: "Soft chocolate, caramel, and dark grain sweetness balanced by clean hop bitterness.",
        mouthfeel: "Medium to medium-full body, smooth.",
        comments: "Lacks the acrid burnt bite of Irish Stout.",
        history: "American craft beer interpretation of historic porters.",
        ingredients: "American pale malt, chocolate malt, crystal malt, American ale yeast.",
        comparison: "Cleaner yeast profile and less acrid than English Porters."
    },
    {
        name: "21A. American IPA",
        stats: "OG: 1.056–1.070 | FG: 1.008–1.014 | IBU: 40–70 | SRM: 6–14 | ABV: 5.5–7.5%",
        impression: "Boldly hopped, bitter American pale ale showcasing citrus/pine hop varieties.",
        aroma: "Intense hop aroma of citrus, pine, stone fruit, or tropical fruit.",
        appearance: "Gold to copper, clear, white head.",
        flavor: "High hop bitterness supported by clean malt. Hop flavor reflects aroma profiles.",
        mouthfeel: "Medium-light to medium body, smooth with no astringency.",
        comments: "The flagship style of the American craft beer revolution.",
        history: "Evolution of traditional English IPAs utilizing bold Pacific Northwest hops.",
        ingredients: "Pale ale malt, crystal malts, US hops (Cascade, Centennial, etc.).",
        comparison: "More hop-forward and cleaner yeast profile than English IPA."
    },
    {
        name: "22A. Double IPA",
        stats: "OG: 1.065–1.085 | FG: 1.008–1.018 | IBU: 60–120 | SRM: 6–14 | ABV: 7.5–10.0%",
        impression: "Intensely hoppy, very strong pale ale with massive hop punch and smooth malt backbone.",
        aroma: "Massive hop explosion (pine, citrus, tropical). Clean alcohol presence.",
        appearance: "Deep gold to light amber, slight haze acceptable, persistent head.",
        flavor: "Intense hop bitterness balanced by powerful malt backbone and smooth warming alcohol.",
        mouthfeel: "Medium-full body, smooth with slight alcohol warmth.",
        comments: "Pushed boundaries of hopping rates in craft brewing.",
        history: "Originated in California in the late 1990s (Vinnie Cilurzo / Pliny the Elder).",
        ingredients: "Pale malt, sugar adjuncts to dry out finish, massive hop loads.",
        comparison: "Stronger, more bitter, and higher alcohol than standard American IPA."
    },
    {
        name: "26C. Belgian Tripel",
        stats: "OG: 1.075–1.085 | FG: 1.008–1.014 | IBU: 20–40 | SRM: 4.5–7 | ABV: 7.5–9.5%",
        impression: "Pale, highly attenuated, spicy/fruity strong Belgian ale with smooth warming finish.",
        aroma: "Complex spicy phenols, light peppery notes, fruity esters (citrus/pear).",
        appearance: "Deep gold to light amber, brilliant clarity, huge rocky white head.",
        flavor: "Crisp dryness, soft spicy malt profile, complex fruit esters.",
        mouthfeel: "Medium-light body, high effervescent carbonation.",
        comments: "Pioneered by Westmalle Trappist monastery.",
        history: "Developed as a stronger version of monastic single/dubbel lines.",
        ingredients: "Pilsner malt, clear candi sugar, Belgian phenolic yeast.",
        comparison: "Paleness and dryness distinguish it from Belgian Dubbel."
    },
    {
        name: "27. Historical Beer (Gose / Piwo Grodziskie)",
        stats: "Stats vary by style (Gose OG: 1.036–1.056 | FG: 1.006–1.010 | IBU: 5–12)",
        impression: "Revived historical specialty styles that predate modern industrial standardization.",
        aroma: "Variable: coriander/lactic sourness in Gose; oak woodsmoke in Grodziskie.",
        appearance: "Variable based on style.",
        flavor: "Reflects ancient grains, salt additions, herbs, or woodsmoke.",
        mouthfeel: "Variable.",
        comments: "Judged strictly against the historical standard entry provided.",
        history: "Styles that faded from commercial prominence but were revived by craft brewers.",
        ingredients: "Malted wheat, barley, coriander, salt, oak-smoked malt.",
        comparison: "Evaluated against historical parameters."
    },
    {
        name: "28. American Wild Ale",
        stats: "Variable depending on base style.",
        impression: "Soured or funky ales utilizing Brettanomyces, Lactobacillus, or Pediococcus.",
        aroma: "Funk, barnyard, leather, or clean sour acidity.",
        appearance: "Variable based on base beer.",
        flavor: "Harmonious balance of wild bacteria/yeast complexity with base beer.",
        mouthfeel: "Typically dry and lightened by high attenuation.",
        comments: "Includes Brett beers and mixed-fermentation sours.",
        history: "American craft adaptations of Belgian lambic and sour traditions.",
        ingredients: "Base malts, wild yeast cultures, souring bacteria.",
        comparison: "Defined by intentional wild microflora inoculation."
    },
    {
        name: "29. Fruit Beer",
        stats: "Variable depending on base style.",
        impression: "Harmonious marriage of fruit and beer, where fruit is evident without overpowering.",
        aroma: "Prominent aromatics of declared fruit.",
        appearance: "Often reflects color or hue of fruit addition.",
        flavor: "Fruit integration balancing base beer malt and hops.",
        mouthfeel: "Variable.",
        comments: "Entrant must declare fruit and base beer style.",
        history: "Traditional European fruit beers and modern craft fruit additions.",
        ingredients: "Base beer, fresh fruit, purees, or juices.",
        comparison: "Judged on balance of fruit and base style."
    },
    {
        name: "30. Spiced Beer",
        stats: "Variable depending on base style.",
        impression: "Harmonious marriage of spices, herbs, or vegetables and beer.",
        aroma: "Aromatics of declared spices/herbs.",
        appearance: "Varies by base beer.",
        flavor: "Balanced spice character without medicinal or harsh notes.",
        mouthfeel: "Varies.",
        comments: "Includes Pumpkin Ales and Winter Seasonals.",
        history: "Ancient gruit tradition updated for modern brewing.",
        ingredients: "Spices, culinary herbs, or vegetables added to base beer.",
        comparison: "Evaluated on spice integration and balance."
    },
    {
        name: "31. Alternative Fermentables Beer",
        stats: "Variable depending on base style.",
        impression: "Beer brewed with non-barley alternative grains or sugars providing distinct character.",
        aroma: "Notes of alternative grain/sugar (rye, honey, spelt).",
        appearance: "Varies.",
        flavor: "Reflects additions such as honey, maple syrup, or rye grain.",
        mouthfeel: "Varies.",
        comments: "Includes Rye Beer and Honey Beer.",
        history: "Utilizing local alternative agricultural products in brewing.",
        ingredients: "Rye, oats, spelt, honey, molasses.",
        comparison: "Judged on distinct contribution of alternative ingredient."
    },
    {
        name: "32. Smoked Beer",
        stats: "Variable depending on base style.",
        impression: "Smoke-enhanced beer showing good balance between woodsmoke and base style.",
        aroma: "Woodsmoke (beech, cherry, peat) balancing base beer notes.",
        appearance: "Varies.",
        flavor: "Harmonious smoke flavor without harshness or ashiness.",
        mouthfeel: "Varies.",
        comments: "Includes Classic Smoked Beer and Specialty Smoked Beer.",
        history: "Reflects historical malt kilning over direct wood fires.",
        ingredients: "Smoked malts, base malts, hops, yeast.",
        comparison: "Smoke must complement, not overwhelm, the base beer."
    },
    {
        name: "33. Wood-Aged Beer",
        stats: "Variable depending on base style.",
        impression: "Beer aged in wood or spirit barrels gaining oak, vanilla, or liquor complexity.",
        aroma: "Wood, vanilla, toasted oak, or spirit notes (bourbon, wine).",
        appearance: "Often slightly darkened by wood contact.",
        flavor: "Barrel character integrated with base beer profile.",
        mouthfeel: "Can add body or drying tannin structure.",
        comments: "Base beer and barrel type must be declared.",
        history: "Craft beer evolution of wood aging and spirit barrel finishing.",
        ingredients: "Base beer, wood barrels (oak), spirits or wine history.",
        comparison: "Judged on synergy between barrel character and base beer."
    },
    {
        name: "34. Commercial Specialty Beer",
        stats: "Variable depending on entrant description.",
        impression: "Experimental, hybrid, or unique novelty beers that do not fit existing categories.",
        aroma: "Varies entirely based on brewer intent.",
        appearance: "Varies.",
        flavor: "Evaluated against entrant's written description.",
        mouthfeel: "Varies.",
        comments: "Entrant must provide detailed description of beer.",
        history: "Designed for innovative craft brewing concepts.",
        ingredients: "Any combination of brewing ingredients.",
        comparison: "Judged against declared entrant specifications."
    }
];
